{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "luxyai.runtimeClaim" . }}
  namespace: {{ include "luxyai.namespace" . }}
  labels:
    {{- include "luxyai.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
