{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "luxyai.serviceAccountName" . }}
  namespace: {{ include "luxyai.namespace" . }}
  labels:
    {{- include "luxyai.labels" . | nindent 4 }}
{{- end }}
